REGISTRATION_POST_QUERIES_LINK = 'https://messenger.tim-ur.ru/backend/register_user.php'
LOGIN_POST_QUERIES_LINK = 'https://messenger.tim-ur.ru/backend/login.php'
CHECK_HANDLE_POST_QUERIES_LINK = 'https://messenger.tim-ur.ru/backend/check_handle.php'
SEND_MESSAGE_POST_QUERIES_LINK = 'https://messenger.tim-ur.ru/backend/send_message.php'
GET_MESSAGES_POST_QUERIES_LINK = 'https://messenger.tim-ur.ru/backend/get_messages.php'
GET_SENDERS_POST_QUERIES_LINK = 'https://messenger.tim-ur.ru/backend/get_message_list.php'
GET_NAME_FROM_HANDLE_POST_QUERIES_LINK = 'https://messenger.tim-ur.ru/backend/get_info.php'
