# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #334;\n"
"color: #fff;")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setStyleSheet("border: 0;")
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sendersScrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.sendersScrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendersScrollArea.sizePolicy().hasHeightForWidth())
        self.sendersScrollArea.setSizePolicy(sizePolicy)
        self.sendersScrollArea.setMinimumSize(QtCore.QSize(100, 0))
        self.sendersScrollArea.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.sendersScrollArea.setFont(font)
        self.sendersScrollArea.setStyleSheet("margin: 0;\n"
"border: 0;\n"
"border-right: 1px solid #668;")
        self.sendersScrollArea.setWidgetResizable(True)
        self.sendersScrollArea.setObjectName("sendersScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 648))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollAreaWidgetContents.setStyleSheet("border: 0;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_panel_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_panel_2.sizePolicy().hasHeightForWidth())
        self.top_panel_2.setSizePolicy(sizePolicy)
        self.top_panel_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top_panel_2.setStyleSheet("border: 0;\n"
"border-radius: 0;")
        self.top_panel_2.setObjectName("top_panel_2")
        self.top_panel = QtWidgets.QHBoxLayout(self.top_panel_2)
        self.top_panel.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.top_panel.setContentsMargins(5, 5, 5, 5)
        self.top_panel.setSpacing(5)
        self.top_panel.setObjectName("top_panel")
        self.new_dialog_btn = QtWidgets.QPushButton(self.top_panel_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_dialog_btn.sizePolicy().hasHeightForWidth())
        self.new_dialog_btn.setSizePolicy(sizePolicy)
        self.new_dialog_btn.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_dialog_btn.setFont(font)
        self.new_dialog_btn.setStyleSheet("background-color: #222;\n"
"border: 1px solid #333;\n"
"border-radius: 10px;")
        self.new_dialog_btn.setObjectName("new_dialog_btn")
        self.top_panel.addWidget(self.new_dialog_btn)
        self.exit_btn = QtWidgets.QPushButton(self.top_panel_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: #222;\n"
"border: 1px solid #333;\n"
"border-radius: 10px;")
        self.exit_btn.setObjectName("exit_btn")
        self.top_panel.addWidget(self.exit_btn)
        self.verticalLayout_4.addWidget(self.top_panel_2)
        self.senders_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.senders_2.setStyleSheet("border-width: 0;\n"
"border-radius: 0;")
        self.senders_2.setObjectName("senders_2")
        self.senders = QtWidgets.QGridLayout(self.senders_2)
        self.senders.setContentsMargins(0, 0, 0, 0)
        self.senders.setSpacing(0)
        self.senders.setObjectName("senders")
        self.verticalLayout_4.addWidget(self.senders_2)
        self.sendersScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.sendersScrollArea)
        self.message_panel = QtWidgets.QWidget(self.centralWidget)
        self.message_panel.setAutoFillBackground(False)
        self.message_panel.setStyleSheet("border: 0;")
        self.message_panel.setObjectName("message_panel")
        self.message_field = QtWidgets.QGridLayout(self.message_panel)
        self.message_field.setContentsMargins(0, 0, 0, 0)
        self.message_field.setSpacing(0)
        self.message_field.setObjectName("message_field")
        self.messangesScrollArea = QtWidgets.QScrollArea(self.message_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messangesScrollArea.sizePolicy().hasHeightForWidth())
        self.messangesScrollArea.setSizePolicy(sizePolicy)
        self.messangesScrollArea.setStyleSheet("border: 0")
        self.messangesScrollArea.setWidgetResizable(True)
        self.messangesScrollArea.setObjectName("messangesScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 600, 530))
        self.scrollAreaWidgetContents_2.setStyleSheet("border: 0;")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messages_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.messages_2.setStyleSheet("border: 0;")
        self.messages_2.setObjectName("messages_2")
        self.messages = QtWidgets.QGridLayout(self.messages_2)
        self.messages.setContentsMargins(11, 11, 11, 11)
        self.messages.setSpacing(0)
        self.messages.setObjectName("messages")
        self.verticalLayout.addWidget(self.messages_2)
        self.messangesScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.message_field.addWidget(self.messangesScrollArea, 1, 0, 1, 1)
        self.info_panel = QtWidgets.QWidget(self.message_panel)
        self.info_panel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.info_panel.setStyleSheet("border-bottom: 1px solid #668;")
        self.info_panel.setObjectName("info_panel")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.info_panel)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.message_field.addWidget(self.info_panel, 0, 0, 1, 1)
        self.send_message_panel = QtWidgets.QWidget(self.message_panel)
        self.send_message_panel.setMaximumSize(QtCore.QSize(16777215, 70))
        self.send_message_panel.setStyleSheet("border: 0;\n"
"border-top: 1px solid #668;")
        self.send_message_panel.setObjectName("send_message_panel")
        self.do_messange = QtWidgets.QHBoxLayout(self.send_message_panel)
        self.do_messange.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.do_messange.setContentsMargins(0, 0, 0, 0)
        self.do_messange.setSpacing(0)
        self.do_messange.setObjectName("do_messange")
        self.messange_input = QtWidgets.QLineEdit(self.send_message_panel)
        self.messange_input.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.messange_input.setFont(font)
        self.messange_input.setStyleSheet("margin: 10px;\n"
"background-color: #555;\n"
"border: 1px solid #444;\n"
"border-radius: 10px")
        self.messange_input.setObjectName("messange_input")
        self.do_messange.addWidget(self.messange_input)
        self.message_send_button = QtWidgets.QPushButton(self.send_message_panel)
        self.message_send_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.message_send_button.setFont(font)
        self.message_send_button.setStyleSheet("background-image: url(\"icons/send_icon.png\");\n"
"/*background-color: #334;*/\n"
"border: 0;\n"
"border-radius: 10px;\n"
"padding: 0 10px;\n"
"margin: 0 5px;")
        self.message_send_button.setObjectName("message_send_button")
        self.do_messange.addWidget(self.message_send_button)
        self.message_field.addWidget(self.send_message_panel, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.message_panel)
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Messenger"))
        self.new_dialog_btn.setText(_translate("MainWindow", "Начать новый диалог"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
        self.message_send_button.setText(_translate("MainWindow", "Отправить"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))
